dist: xenial
language: python
python: 3.7
services:
  - docker
branches:
  only:
    - master
stages:
  - lint
  - test
matrix:
  include:
    - name: lint
      stage: lint
      script:
        - >
          docker run --rm -v $(pwd):/source -w /source python bash -c "
          pip install flake8;
          flake8 pytest_automock tests"
    - name: cpython 3.6
      stage: test
      script:
        - >
          docker run --rm -v $(pwd):/source -w /source python:3.6 bash -c "
          pip install -e ./[dev];
          pytest;"
    - name: cpython 3.7
      stage: test
      script:
        - >
          docker run --rm -v $(pwd):/source -w /source python:3.7 bash -c "
          pip install -e ./[dev];
          pytest;"
    - name: cpython 3.8
      stage: test
      install:
        - pip install codecov
      script:
        - >
          docker run --rm -v $(pwd):/source -w /source \
                     -e COV_CORE_SOURCE=pytest_automock \
                     -e COV_CORE_CONFIG=.coveragerc \
                     -e COV_CORE_DATAFILE=.coverage.eager \
                     python:3.8 bash -c "
          pip install -e ./[dev];
          pytest;"
      after_success:
        - codecov
deploy:
  provider: pypi
  user: __token__
  password:
    secure: DyzVd4LJKmQKSq/3M2zjoze/koCEN9cNXhoZelnaPBIgoNHzG0AsDheufPnZ4oXHw9YHSAF0MPE4GZVvQW0lePMcEa3h8CDzdipYDkCz1IwqgLyD0Kh6pIF99kngyp0ZKuCvVbxGcetLA0I9iV2AHI5DJb9E0GCr+v6sd8Z6ZhfNRws+2XbgW/MK98aPg9v9CuZ3J+SQSER1aYLD1EDDLDQ/NEM3GoNDlY/gFfFmwENHTJeU6iqo4Bx+5q8aTDFm+xKn/gA3SF5Jysq66/373mMBrlLGmI0S2lt4qJWJ7gYAsdoQmKkvPZbF4wrDUT+SKLmlk2VNUaU0ZP5uXY0dUYXg78bM4l5jxqNHGuXmGjVH3URnYdSurmeLgvLaDnmxOiEcWkTmq2ZxRIAB8g+0x8pMDpHsign/Qs5yWPhhKeeLLap78RiRgfZQXexTToXa5JIw7dDU0uT62Rc8Lxfd4+c2cqegkKjioQ5vV3sMmDg7uHKftHqtK0Zh30VS0YT3Z1sVYmX5ENDaGoNDE+XUmINSczIwzUrQ1TvyJ9BHVUf6njGeXwcpO/aHsHkZxfk9oPr/xKrv3KilrT0TpmG9JhiI86da8Icf8rtg4mYD1bk5r7M7U7Z33GU6IhzhzRxUT5xd57iKGO549mEzcsmJuWoJCvIjqhxUyTtukggu+MM=
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    branch: master
