dist: xenial
language: python
python: 3.7
services:
  - docker
branches:
  only:
    - master
stages:
  - lint
  - test
matrix:
  include:
    - name: lint
      stage: lint
      script:
        - >
          docker run --rm -v $(pwd):/source -w /source python bash -c "
          pip install flake8;
          flake8 pytest_automock tests"
    - name: cpython 3.7
      stage: test
      script:
        - >
          docker run --rm -v $(pwd):/source -w /source python:3.7 bash -c "
          pip install -e ./[dev];
          pytest;"
    - name: cpython 3.8
      stage: test
      install:
        - pip install codecov
      script:
        - >
          docker run --rm -v $(pwd):/source -w /source \
                     -e COV_CORE_SOURCE=pytest_automock \
                     -e COV_CORE_CONFIG=.coveragerc \
                     -e COV_CORE_DATAFILE=.coverage.eager \
                     python:3.8 bash -c "
          pip install -e ./[dev];
          pytest;"
      after_success:
        - codecov
